### ISSUE TITLE
aoc-processing: not all files in librarian staged

### ISSUE THREAD

**Issue by nkern** [HERA-Team/HERA_plots#3]
I've tried running the `run_notebook.sh` script, and also the `librarian_stage_files.py` command-line function for some test data and I'm noticing that it sometimes doesn't stage all of the data present in the librarian. If you run it on 1191254462, for example, it only stages the `calfits` files, even though other files are present on `herastore`. Let me know if you @pkgw have run into this issue yourself.

**Comment by nkern** [comment]
I think it has to do with the "or" statements in the JSON search string. It is only matching the last "name-matches" criterion for some reason.

**Comment by nkern** [comment]
current workaround is to make 4 separate `librarian_stage_files.py` calls:
```
search="{\"session-id-is-exactly\": $sessid, \"name-matches\": \"%.HH.uv\"}"
librarian_stage_files.py --wait local "$staging_dir" "$search"
search="{\"session-id-is-exactly\": $sessid, \"name-matches\": \"%.HH.uvOR\"}"
librarian_stage_files.py --wait local "$staging_dir" "$search"
search="{\"session-id-is-exactly\": $sessid, \"name-matches\": \"%.json\"}"
librarian_stage_files.py --wait local "$staging_dir" "$search"
search="{\"session-id-is-exactly\": $sessid, \"name-matches\": \"%.calfits\"}"
librarian_stage_files.py --wait local "$staging_dir" "$search"
```

**Comment by pkgw** [comment]
Oh, duh; making a dictionary with four items labeled "name-matches" is just like trying to put four items with the same key into a Python dict. You get left with just the last one. Your workaround works, or I'll try to think of a smarter way to construct the query.

**Comment by pkgw** [comment]
OK, [I have an idea for how to make it easier to write such queries](https://github.com/HERA-Team/librarian/issues/42). But for the time being it is probably best to proceed with the workaround. Please commit and push the fix when you have the chance.
